/**
 * drillModel.js — the deterministic brain of Exam Drill.
 *
 * WHY THIS FILE EXISTS
 * ────────────────────
 * The drill is "adaptive", but adaptivity is not an excuse for a black box.
 * Everything that decides what the student sees next, when they are told where
 * they stand, and what counts as knowing something lives here as pure
 * functions over a plain state object. The LLM writes questions; this file
 * decides which question to ask for. That split is deliberate: a generator
 * that also picks its own next move cannot be tested, and every rule below
 * came out of measured production data we would lose the moment it drifted.
 *
 * THE MEASUREMENT THIS WHOLE FILE IS BUILT AROUND (2026-08-31, n=68 students,
 * 1,081 graded answers from users/{uid}/studyPerformance.formats):
 *
 *              MCQ      SATA     case study
 *   Pro       81.7%     29.6%      14.8%
 *   Free      88.2%     43.2%      22.2%
 *
 * A ~59pp gap in BOTH cohorts. The consequence is the single most important
 * rule in the drill: a readiness verdict derived from MCQ alone is a lie. A
 * student at 82% on multiple choice is at ~22% on the formats her exam
 * actually uses, and telling her she is ready is the worst thing the product
 * can do. Hence `hasFormatEvidence` gating every strength claim, and the
 * first-block composition quota that guarantees she meets SATA and a case
 * study inside her first five questions.
 *
 * WHY TWO ANSWERS, NOT ONE, FOR A STRENGTH CLAIM
 * ──────────────────────────────────────────────
 * Borrowed from DIAGNOSTIC_QUESTION_COUNT in the backend: one question on four
 * options is a coin flip, and the cost of that coin landing wrong is not a
 * wasted question, it is telling her she is solid on something she will meet
 * again on the exam. Weakness needs less evidence than strength, because the
 * cost of over-drilling a topic is a few minutes and the cost of skipping a
 * real gap is the exam.
 *
 * BLOCK SIZES: 5 THEN 10
 * ──────────────────────
 * 39% of study sessions stop at or before node 1, and three of our eight
 * paying users completed zero nodes. Ten questions is too long to wait for the
 * first proof that the thing understands you, so the opening block is 5. After
 * that the cadence settles at 10, which is long enough for the topic × format
 * grid to say something that is not noise.
 */

import { findMatchingTopicKey } from '../../Services/topicKey';

/* ── Formats ──────────────────────────────────────────────────────────────
 * Mirrors the renderers StudyExamCard already routes to, and the `format`
 * values recorded by updateStudyPerformance. "unfoldingCase" is generated by
 * the backend as a case-study variant and is bucketed with it everywhere:
 * the student experiences one clinical scenario either way, and splitting the
 * bucket would halve an already-small sample.
 */
export const FORMATS = ['mcq', 'sata', 'casestudy'];

/** Formats that actually discriminate readiness. See the table in the header. */
export const HARD_FORMATS = ['sata', 'casestudy'];

/** Normalize any generator/legacy spelling onto a FORMATS member. */
export const normalizeFormat = (raw) => {
  if (raw === 'unfoldingCase' || raw === 'caseStudy' || raw === 'case_study') return 'casestudy';
  return FORMATS.includes(raw) ? raw : 'mcq';
};

/* ── Block & checkpoint cadence ───────────────────────────────────────── */

/** Questions in the opening block — short on purpose, see header. */
export const FIRST_BLOCK_SIZE = 5;

/** Questions per block after the first. */
export const BLOCK_SIZE = 10;

/**
 * Case studies allowed per block.
 *
 * The meter charges a flat 1 for a case study (product decision: it is our
 * sharpest instrument and should be the cheapest insight a free user can buy),
 * but it costs the STUDENT ~150s against ~60s for an MCQ. Without a cap, "10
 * questions to your checkpoint" swings between 10 and 25 minutes and stops
 * being a promise. The cap keeps block length predictable while the quota
 * below still guarantees the format gets met.
 */
export const CASESTUDY_CAP_FIRST_BLOCK = 1;
export const CASESTUDY_CAP_PER_BLOCK = 2;

/** Answers needed on a topic+format before we will call it a strength. */
export const MIN_EVIDENCE_STRONG = 2;

/** Accuracy at or above this (with enough evidence) reads as demonstrated. */
export const STRONG_ACCURACY = 0.8;

/** Accuracy at or below this reads as a genuine gap, not a wobble. */
export const WEAK_ACCURACY = 0.4;

/**
 * Percentage-point gap between MCQ and non-MCQ accuracy that we are willing to
 * call a format problem out loud. 25pp is well inside the ~59pp we measure
 * across the whole user base, so this fires on real cases without needing the
 * student to be an outlier.
 */
export const FORMAT_GAP_PP = 25;

/**
 * Multiple-choice accuracy below which we will not say she knows the material,
 * however wide the gap underneath it.
 *
 * The format-gap sentence makes TWO claims: the hard formats are worse (a
 * comparison) and the material itself is known (an absolute). Only the
 * comparison was ever checked. So a student sitting at 33% on multiple choice
 * and 0% on select-all cleared the 25pp bar and was told she knew her
 * material — a 33-point gap between two failing scores. That is a knowledge
 * problem wearing a format problem's clothes, and acting on it sends her to
 * drill SATA technique when what is missing is the content.
 *
 * Deliberately below STRONG_ACCURACY: a student at 72% on multiple choice and
 * 10% on select-all really does have a format problem, and we should still
 * say so.
 */
export const FORMAT_GAP_MIN_MCQ = 0.7;

/** Answers needed before we will characterise the drill as a whole. */
export const MIN_EVIDENCE_OVERALL = 3;

/**
 * Overall accuracy at or below which the drill stops hunting for a pattern and
 * says the plain thing. Same line as a weak topic: what makes one topic a gap
 * makes every topic a different conversation.
 */
export const STRUGGLING_ACCURACY = WEAK_ACCURACY;

/** A concept missed this many times is a misconception, not bad luck. */
export const MISCONCEPTION_MIN_MISSES = 2;

/* ── State ────────────────────────────────────────────────────────────── */

/**
 * @typedef {Object} DrillState
 * @property {number} answered            Total questions answered.
 * @property {Array}  history             One row per answer, in order.
 * @property {Object} topics              topic -> format -> { correct, total }
 * @property {Object} formats             format -> { correct, total }
 * @property {Object} concepts            conceptKey -> { correct, total, label }
 * @property {number} difficulty          1..3, current target difficulty.
 * @property {number} streak              Consecutive correct (negative = wrong).
 * @property {string[]} askedHashes       Anti-repeat keys for the generator.
 * @property {number} lastCheckpointAt    `answered` value at the last checkpoint.
 */

/** Fresh drill state. `topicPool` seeds the topics we intend to cover. */
export const createDrillState = (topicPool = []) => ({
  answered: 0,
  history: [],
  topics: {},
  formats: {},
  concepts: {},
  difficulty: 1,
  streak: 0,
  askedHashes: [],
  lastCheckpointAt: 0,
  topicPool: topicPool.filter(Boolean),
});

const emptyBucket = () => ({ correct: 0, total: 0 });

/**
 * Which bucket an answer belongs in.
 *
 * The topic on an answer is whatever the GENERATOR called it, and the
 * generator has no memory between calls — so one subject arrives as "Sleep and
 * Testosterone", then "Testosterone and Sleep", then "Sleep Restriction and
 * Testosterone". Keyed raw, that was one student's evidence split three ways:
 * 14 answers across 9 topics, none of them reaching MIN_EVIDENCE_STRONG, so
 * classifyTopic had nothing to say about any of them and the checkpoint fell
 * through every finding it has.
 *
 * Buckets that already hold answers are offered first, so an answer merges
 * into evidence rather than into an empty name from the plan.
 *
 * This is the same matcher that already decides the buckets in
 * users/{uid}/studyPerformance, which updateStudyPerformance writes from the
 * SAME handler. Before this the two stores disagreed about how many subjects
 * the student had been asked about.
 */
export const resolveTopic = (state, raw) => {
  const name = (raw || 'General').trim() || 'General';
  const known = [
    ...Object.keys(state?.topics || {}),
    ...(state?.topicPool || []),
  ].filter(Boolean);
  return findMatchingTopicKey(name, [...new Set(known)]) || name;
};

const bump = (bucket, correct) => ({
  correct: bucket.correct + (correct ? 1 : 0),
  total: bucket.total + 1,
});

/**
 * Fold one answered question into the model.
 *
 * Partial credit (SATA 3-of-4, a case study with 2 of 3 steps ordered right)
 * is recorded on `history` for display but graded here as NOT correct. The
 * student needs the sting, and a model that counts near-misses as knowledge
 * reproduces exactly the false confidence the format gap exposes. `isCorrect`
 * from the renderers already means "fully correct".
 *
 * WHAT A ROW IS FOR
 * ─────────────────
 * `history` is the drill's event log, and the aggregate buckets above it are
 * only a cached read of it. Every row therefore carries what it took to answer
 * as well as whether it was right: the format, the partial score, HOW LONG it
 * took, and WHEN. Accuracy alone cannot tell a student who is guessing from
 * one who is working — a wrong answer in nine seconds and a wrong answer in
 * ninety are different problems with different fixes, and the drill had been
 * throwing that distinction away (`elapsed` was counted for the clock and
 * then dropped on submit).
 *
 * `at` is an ISO string, never serverTimestamp(): these are compared
 * client-side, and sentinels do not survive the round trip in the shapes we
 * store. Same rule as the concept ledger and node `completedAt`.
 *
 * Rows written before this change have neither field. Every reader must treat
 * `seconds` and `at` as optional rather than assuming a resumed drill has
 * them.
 *
 * @param {DrillState} state
 * @param {Object} answer  { topic, format, isCorrect, score, maxScore, seconds, concept, conceptKey, hash }
 * @returns {DrillState} a new state; the input is not mutated.
 */
export const recordAnswer = (state, answer) => {
  const format = normalizeFormat(answer?.format);
  const topic = resolveTopic(state, answer?.topic);
  const correct = !!answer?.isCorrect;

  const topicRow = state.topics[topic] || {};
  const nextTopics = {
    ...state.topics,
    [topic]: { ...topicRow, [format]: bump(topicRow[format] || emptyBucket(), correct) },
  };

  const nextFormats = {
    ...state.formats,
    [format]: bump(state.formats[format] || emptyBucket(), correct),
  };

  // Concept ledger. Keyed on the generator's short label, never on question
  // text — the same misconception phrased two ways must land in one bucket.
  // A missing key is skipped rather than fabricated (same rule as conceptLedger).
  let nextConcepts = state.concepts;
  const key = answer?.conceptKey;
  if (key) {
    const prev = state.concepts[key] || { correct: 0, total: 0, label: key, topic };
    nextConcepts = {
      ...state.concepts,
      [key]: { ...prev, ...bump(prev, correct), label: prev.label || key, topic: prev.topic || topic },
    };
  }

  const streak = correct
    ? Math.max(1, state.streak + 1)
    : Math.min(-1, state.streak - 1);

  return {
    ...state,
    answered: state.answered + 1,
    history: [
      ...state.history,
      {
        index: state.answered,
        topic,
        format,
        isCorrect: correct,
        score: answer?.score ?? (correct ? 1 : 0),
        maxScore: answer?.maxScore ?? 1,
        seconds: Number.isFinite(answer?.seconds) ? Math.round(answer.seconds) : null,
        at: answer?.at || new Date().toISOString(),
        concept: answer?.concept || null,
        conceptKey: key || null,
        difficulty: state.difficulty,
      },
    ],
    topics: nextTopics,
    formats: nextFormats,
    concepts: nextConcepts,
    streak,
    difficulty: nextDifficulty(state.difficulty, streak),
    askedHashes: answer?.hash ? [...state.askedHashes, answer.hash] : state.askedHashes,
  };
};

/**
 * Difficulty drifts, it does not jump. Three right in a row earns a step up,
 * two wrong earns a step down. Asymmetric on purpose: climbing should be
 * earned, falling should be quick, because a student drowning at difficulty 3
 * learns nothing and leaves.
 */
export const nextDifficulty = (current, streak) => {
  if (streak >= 3) return Math.min(3, current + 1);
  if (streak <= -2) return Math.max(1, current - 1);
  return current;
};

/* ── Classification ───────────────────────────────────────────────────── */

/** Sum buckets across every format for one topic. */
export const topicTotals = (state, topic) => {
  const row = state.topics[topic] || {};
  return Object.values(row).reduce(
    (acc, b) => ({ correct: acc.correct + b.correct, total: acc.total + b.total }),
    emptyBucket()
  );
};

/** Does this topic have any evidence from a format that actually discriminates? */
export const hasFormatEvidence = (state, topic) => {
  const row = state.topics[topic] || {};
  return HARD_FORMATS.some((f) => (row[f]?.total || 0) > 0);
};

/**
 * What we currently know about a topic. The four states are deliberately
 * distinct — "we have not asked enough" is not the same claim as "she is
 * inconsistent", and collapsing them is how a product starts lying.
 *
 * `provisional` is the one that matters commercially: she looks strong, but
 * only on MCQ, which per the header measurement means we know almost nothing
 * about whether she can do it on the exam.
 *
 * @returns {'untested'|'insufficient'|'provisional'|'weak'|'inconsistent'|'strong'}
 */
export const classifyTopic = (state, topic) => {
  const { correct, total } = topicTotals(state, topic);
  if (total === 0) return 'untested';
  if (total < MIN_EVIDENCE_STRONG) return 'insufficient';

  const acc = correct / total;
  if (acc <= WEAK_ACCURACY) return 'weak';
  if (acc >= STRONG_ACCURACY) return hasFormatEvidence(state, topic) ? 'strong' : 'provisional';
  return 'inconsistent';
};

/** Accuracy over a set of formats, or null when there is no evidence at all. */
export const accuracyOver = (state, formats) => {
  let correct = 0;
  let total = 0;
  formats.forEach((f) => {
    const b = state.formats[f];
    if (b) {
      correct += b.correct;
      total += b.total;
    }
  });
  return total === 0 ? null : { correct, total, accuracy: correct / total };
};

/**
 * The format diagnosis — "you know this material, you cannot yet do it in SATA
 * form" — or null when we have not earned the right to say it.
 */
export const formatDiagnosis = (state) => {
  const mcq = accuracyOver(state, ['mcq']);
  const hard = accuracyOver(state, HARD_FORMATS);
  if (!mcq || !hard) return null;
  if (mcq.total < MIN_EVIDENCE_STRONG || hard.total < MIN_EVIDENCE_STRONG) return null;

  // The comparison is not enough on its own: the sentence this feeds also
  // claims she KNOWS the material, and two failing scores 30 points apart do
  // not support that.
  if (mcq.accuracy < FORMAT_GAP_MIN_MCQ) return null;

  const gapPp = Math.round((mcq.accuracy - hard.accuracy) * 100);
  if (gapPp < FORMAT_GAP_PP) return null;

  // Which hard format is worst — that is what we recommend drilling.
  //
  // Ties break toward the format we have MORE evidence on. Both sitting at 0%
  // is common early on, and recommending the one seen once over the one seen
  // four times would send her to drill the format we know least about, on the
  // strength of a single answer.
  const worst = HARD_FORMATS
    .map((f) => ({ format: f, ...(state.formats[f] || { correct: 0, total: 0 }) }))
    .filter((b) => b.total > 0)
    .map((b) => ({ ...b, accuracy: b.correct / b.total }))
    .sort((a, b) => (a.accuracy - b.accuracy) || (b.total - a.total))[0] || null;

  return { gapPp, mcq, hard, worst };
};

/**
 * The drill as a whole.
 *
 * Counted over `history` rather than `answered` because history is what the
 * numerator counts too — a resumed drill trimmed at DRILL_HISTORY_CAP would
 * otherwise divide by a number its correct-count never saw.
 */
export const overallAccuracy = (state) => {
  const total = (state?.history || []).length;
  if (!total) return null;
  const correct = state.history.filter((h) => h.isCorrect).length;
  return { correct, total, accuracy: correct / total };
};

/**
 * Missing it across the board — not a format effect, not one bad topic.
 *
 * This is the case the checkpoint had no sentence for. With every topic still
 * below MIN_EVIDENCE_STRONG nothing reaches the weak bucket, so a student who
 * had answered one of five correctly fell through every finding and was told
 * "nothing has fallen over yet".
 */
export const isStrugglingBroadly = (state) => {
  const overall = overallAccuracy(state);
  if (!overall || overall.total < MIN_EVIDENCE_OVERALL) return false;
  return overall.accuracy <= STRUGGLING_ACCURACY;
};

/**
 * Her first ever fully-correct answer in a hard format, when it landed inside
 * the block just finished.
 *
 * WHY A MILESTONE AND NOT A TREND
 * ──────────────────────────────
 * Every other reading on this screen is cumulative and memoryless: the
 * checkpoint recomputes from the running totals and has no idea what it said
 * last time. So a student who got her first select-all right after eleven
 * failed ones saw the aggregate move 0% → 8% and heard nothing about it, which
 * is the one moment the drill should have noticed.
 *
 * The honest way to notice it is NOT to call it improvement. One right answer
 * in ten is not a trend, and "you are improving" on that evidence is the same
 * unearned claim as FORMAT_GAP_MIN_MCQ exists to prevent. What IS true, and
 * worth saying, is the fact: this format has gone from never to once, so it is
 * no longer something she cannot do at all.
 *
 * One correct hard answer in TOTAL is what makes it "first" even when history
 * has been trimmed at DRILL_HISTORY_CAP — the aggregate buckets are never trimmed, so
 * one correct hard answer in total means the row we find is that answer.
 */
export const firstHardWinInBlock = (state) => {
  if (!state) return null;
  const hardCorrect = HARD_FORMATS.reduce(
    (n, f) => n + (state.formats?.[f]?.correct || 0),
    0
  );
  if (hardCorrect !== 1) return null;

  const since = state.lastCheckpointAt || 0;
  const row = (state.history || []).find(
    (h) => HARD_FORMATS.includes(h.format) && h.isCorrect
  );
  if (!row || (row.index ?? 0) < since) return null;
  return { format: row.format, index: row.index };
};

/** Concepts missed enough times to call a pattern rather than a slip. */
export const repeatedMisconceptions = (state) =>
  Object.entries(state.concepts)
    .map(([key, c]) => ({ key, ...c, misses: c.total - c.correct }))
    .filter((c) => c.misses >= MISCONCEPTION_MIN_MISSES)
    .sort((a, b) => b.misses - a.misses);

/* ── Block geometry ───────────────────────────────────────────────────── */

/** Which block `answered` falls in. Block 0 is the short opener. */
export const blockIndexAt = (answered) =>
  answered < FIRST_BLOCK_SIZE ? 0 : 1 + Math.floor((answered - FIRST_BLOCK_SIZE) / BLOCK_SIZE);

/** Nominal size of a block, ignoring budget. */
export const nominalBlockSize = (blockIndex) =>
  blockIndex === 0 ? FIRST_BLOCK_SIZE : BLOCK_SIZE;

/** How many questions have been answered inside the current block. */
export const answeredInBlock = (answered) => {
  const idx = blockIndexAt(answered);
  const start = idx === 0 ? 0 : FIRST_BLOCK_SIZE + (idx - 1) * BLOCK_SIZE;
  return answered - start;
};

/**
 * Size of the block we are actually going to run.
 *
 * WHY BUDGET SHORTENS THE BLOCK RATHER THAN CUTTING IT OFF
 * The checkpoint IS the product. A free user with 4 questions of budget who
 * starts a 10-block meets the SATA/case-study wall, gets told nothing, and
 * hits a paywall holding only the sting. So when the remaining allowance
 * cannot cover a full block we run a SHORT block and still deliver the
 * checkpoint at the end of it. The meter is untouched — every question is
 * still exactly one unit — the block just ends where the budget does.
 *
 * @param {number} blockIndex
 * @param {number} remaining  Questions the user can still afford (Infinity for pro).
 */
export const plannedBlockSize = (blockIndex, remaining) => {
  const nominal = nominalBlockSize(blockIndex);
  if (!Number.isFinite(remaining)) return nominal;
  return Math.max(1, Math.min(nominal, remaining));
};

/** Case studies permitted in a block of this index. */
export const caseStudyCap = (blockIndex) =>
  blockIndex === 0 ? CASESTUDY_CAP_FIRST_BLOCK : CASESTUDY_CAP_PER_BLOCK;

/**
 * Formats a block MUST contain before it ends.
 *
 * The opening block owes the student a SATA and a case study. This is the
 * whole conversion mechanism and the reason the drill is honest: ~39% of study
 * sessions stop at or before the first node, so under the old MCQ-first
 * ordering four in ten students only ever met the one format they are already
 * good at, aced it, and left believing they were ready.
 *
 * A block shortened by budget keeps the requirement but drops what will not
 * fit, hardest-first: with 2 questions left you still meet a case study.
 */
export const requiredFormatsForBlock = (blockIndex, size) => {
  if (blockIndex !== 0) return [];
  const wanted = ['casestudy', 'sata'];
  // Leave at least one slot for the MCQ on-ramp when the block is full length.
  const room = size >= FIRST_BLOCK_SIZE ? wanted.length : Math.max(0, size - 1);
  return wanted.slice(0, room);
};

/* ── Checkpoints ──────────────────────────────────────────────────────── */

/**
 * Should we stop and tell her where she stands?
 *
 * True at the end of a block, or when the budget-shortened block has run out.
 * Never twice for the same answer count.
 */
export const shouldCheckpoint = (state, remainingAtBlockStart = Infinity) => {
  if (state.answered === 0) return false;
  if (state.answered === state.lastCheckpointAt) return false;
  const idx = blockIndexAt(state.answered - 1);
  const size = plannedBlockSize(idx, remainingAtBlockStart);
  return answeredInBlock(state.answered - 1) + 1 >= size;
};

/** How many more questions until the next checkpoint. */
export const questionsUntilCheckpoint = (state, remaining = Infinity) => {
  const idx = blockIndexAt(state.answered);
  const size = plannedBlockSize(idx, remaining);
  return Math.max(0, size - answeredInBlock(state.answered));
};

/**
 * Build the checkpoint the student actually reads.
 *
 * Deliberately NOT a score. A percentage is the one number that lets her keep
 * believing the average — the whole point of the topic × format grid is that
 * "69%" is usually not a knowledge level, it is a strong MCQ score dragged
 * down by two formats she cannot do.
 *
 * @returns {{
 *   answered: number, correct: number,
 *   strengths: Array, provisional: Array, inconsistent: Array, weak: Array,
 *   formatGap: Object|null, misconceptions: Array,
 *   recommendation: { kind: string, topic: ?string, format: ?string }
 * }}
 */
export const buildCheckpoint = (state) => {
  const buckets = { strong: [], provisional: [], inconsistent: [], weak: [], insufficient: [] };

  Object.keys(state.topics).forEach((topic) => {
    const verdict = classifyTopic(state, topic);
    if (!buckets[verdict]) return;
    const { correct, total } = topicTotals(state, topic);
    buckets[verdict].push({ topic, correct, total, accuracy: total ? correct / total : 0 });
  });

  const byWeakest = (a, b) => a.accuracy - b.accuracy;
  Object.values(buckets).forEach((list) => list.sort(byWeakest));

  const gap = formatDiagnosis(state);
  const misconceptions = repeatedMisconceptions(state);
  const correct = state.history.filter((h) => h.isCorrect).length;
  const struggling = isStrugglingBroadly(state);
  const firstHardWin = firstHardWinInBlock(state);

  return {
    answered: state.answered,
    correct,
    strengths: buckets.strong,
    provisional: buckets.provisional,
    inconsistent: buckets.inconsistent,
    weak: buckets.weak,
    insufficient: buckets.insufficient,
    formatGap: gap,
    struggling,
    firstHardWin,
    misconceptions,
    recommendation: recommendNext(state, buckets, gap, misconceptions, struggling),
  };
};

/**
 * What to practise next. Ordered by what actually costs marks on the exam.
 *
 * A format gap outranks a weak topic because it applies to EVERY topic at
 * once: a student who cannot do SATA loses those marks across the whole paper,
 * whereas a weak topic loses her the questions on that topic.
 */
export const recommendNext = (state, buckets, gap, misconceptions, struggling = false) => {
  if (gap && gap.worst) {
    return { kind: 'format', format: gap.worst.format, topic: null };
  }
  if (buckets.weak.length) {
    return { kind: 'weakTopic', topic: buckets.weak[0].topic, format: null };
  }
  if (misconceptions.length) {
    return { kind: 'misconception', topic: misconceptions[0].topic || null, format: null, concept: misconceptions[0].label };
  }
  if (buckets.inconsistent.length) {
    return { kind: 'inconsistentTopic', topic: buckets.inconsistent[0].topic, format: null };
  }
  if (buckets.provisional.length) {
    return { kind: 'proveIt', topic: buckets.provisional[0].topic, format: 'sata' };
  }
  // Nothing specific has surfaced and most of it is going wrong. Widening to a
  // topic she has not met is the drill changing the subject: "nothing left to
  // prove here" is a sentence she has earned the right to disbelieve.
  if (struggling) return { kind: 'foundations', topic: null, format: null };

  const untested = untestedTopics(state);
  if (untested.length) return { kind: 'newTopic', topic: untested[0], format: null };
  return { kind: 'broaden', topic: null, format: null };
};

/** Topics from the pool we have never asked about. */
export const untestedTopics = (state) =>
  (state.topicPool || []).filter((t) => !state.topics[t] || topicTotals(state, t).total === 0);

/* ── Next-question policy ─────────────────────────────────────────────── */

/**
 * Decide what to ASK FOR next. Returns a spec the generator fills in; it never
 * writes a question itself.
 *
 * The order of these rules is the product. Read it top to bottom as a
 * sentence: honour what the block owes her, close a real gap, then refuse to
 * let an MCQ-only "strength" stand, then gather missing evidence, then widen.
 *
 * @param {DrillState} state
 * @param {Object} opts { remaining, blockFormatsUsed }
 * @returns {{ format, topic, difficulty, reason }}
 */
export const selectNextSpec = (state, opts = {}) => {
  const remaining = opts.remaining ?? Infinity;
  const blockIndex = blockIndexAt(state.answered);
  const size = plannedBlockSize(blockIndex, remaining);
  const used = opts.blockFormatsUsed || {};
  const slotsLeft = size - answeredInBlock(state.answered);

  const difficulty = state.difficulty;

  // 1. Block debts. If the slots remaining exactly cover the formats this
  //    block still owes, we stop choosing and start paying.
  const required = requiredFormatsForBlock(blockIndex, size);
  const unmet = required.filter((f) => !used[f]);
  if (unmet.length > 0 && slotsLeft <= unmet.length) {
    return {
      format: unmet[0],
      topic: pickTopicForProbe(state),
      difficulty,
      reason: 'blockFormatQuota',
    };
  }

  const capReached = (used.casestudy || 0) >= caseStudyCap(blockIndex);

  // 2. A demonstrated gap gets drilled, in a hard format — re-asking a weak
  //    topic as MCQ tells us nothing we do not already know.
  const weak = rankedTopics(state, 'weak')[0];
  if (weak) {
    return {
      format: preferredHardFormat(state, weak.topic, capReached),
      topic: weak.topic,
      difficulty: Math.max(1, difficulty - 1),
      reason: 'drillWeak',
    };
  }

  // 3. Looks strong, but only on multiple choice. This is the prober that
  //    stops the product from congratulating someone into an exam failure.
  const provisional = rankedTopics(state, 'provisional')[0];
  if (provisional) {
    return {
      format: preferredHardFormat(state, provisional.topic, capReached),
      topic: provisional.topic,
      difficulty,
      reason: 'proveStrength',
    };
  }

  // 4. Not enough evidence yet to say anything at all.
  const thin = rankedTopics(state, 'insufficient')[0];
  if (thin) {
    return {
      format: leastTestedFormat(state, thin.topic, capReached),
      topic: thin.topic,
      difficulty,
      reason: 'gatherEvidence',
    };
  }

  // 5. Inconsistent — keep sampling until it resolves one way or the other.
  const wobbly = rankedTopics(state, 'inconsistent')[0];
  if (wobbly) {
    return {
      format: leastTestedFormat(state, wobbly.topic, capReached),
      topic: wobbly.topic,
      difficulty,
      reason: 'resolveInconsistency',
    };
  }

  // 6. Nothing owing — widen the map.
  const fresh = untestedTopics(state)[0];
  return {
    format: fresh ? 'mcq' : leastTestedFormatOverall(state, capReached),
    topic: fresh || pickTopicForProbe(state),
    difficulty,
    reason: fresh ? 'newTopic' : 'broaden',
  };
};

/** Topics with a given verdict, weakest first. */
export const rankedTopics = (state, verdict) =>
  Object.keys(state.topics)
    .filter((t) => classifyTopic(state, t) === verdict)
    .map((topic) => ({ topic, ...topicTotals(state, topic) }))
    .sort((a, b) => (a.correct / a.total) - (b.correct / b.total));

/** The hard format we have least evidence on for this topic. */
export const preferredHardFormat = (state, topic, capReached) => {
  const row = state.topics[topic] || {};
  const pool = capReached ? ['sata'] : HARD_FORMATS;
  return [...pool].sort((a, b) => (row[a]?.total || 0) - (row[b]?.total || 0))[0] || 'sata';
};

/** Least-tested format for a topic, respecting the case-study cap. */
export const leastTestedFormat = (state, topic, capReached) => {
  const row = state.topics[topic] || {};
  const pool = capReached ? FORMATS.filter((f) => f !== 'casestudy') : FORMATS;
  return [...pool].sort((a, b) => (row[a]?.total || 0) - (row[b]?.total || 0))[0] || 'mcq';
};

/** Least-tested format across the whole drill. */
export const leastTestedFormatOverall = (state, capReached) => {
  const pool = capReached ? FORMATS.filter((f) => f !== 'casestudy') : FORMATS;
  return [...pool].sort((a, b) => (state.formats[a]?.total || 0) - (state.formats[b]?.total || 0))[0] || 'mcq';
};

/** A reasonable topic to hang a probe on when no topic is indicated. */
export const pickTopicForProbe = (state) => {
  const fresh = untestedTopics(state)[0];
  if (fresh) return fresh;
  const known = Object.keys(state.topics);
  if (!known.length) return (state.topicPool || [])[0] || null;
  return known
    .map((topic) => ({ topic, ...topicTotals(state, topic) }))
    .sort((a, b) => a.total - b.total)[0].topic;
};

/**
 * Formats used so far inside the current block — the generator loop needs this
 * to honour the quota and the cap, and it is derivable, so we never store it.
 */
export const blockFormatsUsed = (state) => {
  const idx = blockIndexAt(state.answered);
  const start = idx === 0 ? 0 : FIRST_BLOCK_SIZE + (idx - 1) * BLOCK_SIZE;
  const used = {};
  state.history.slice(start).forEach((h) => {
    used[h.format] = (used[h.format] || 0) + 1;
  });
  return used;
};
