import React, { useEffect } from 'react';
import { Link } from 'react-router-dom';
import './NclexQuestionGenerator.css';

const NclexQuestionGenerator = () => {
  useEffect(() => {
    document.title = 'Free AI NCLEX Question Generator | NurseQuizAI';
    const meta = document.querySelector('meta[name="description"]');
    if (meta) meta.setAttribute('content', 'Generate unlimited NCLEX-style practice questions from your own nursing notes in seconds. Supports NGN, SATA, pharmacology, and more. Free to start.');
  }, []);

  return (
    <div className="lp-page">

      {/* ── NAV ── */}
      <nav className="lp-nav" aria-label="Main navigation">
        <Link to="/" className="lp-nav-brand">
          <img src="/NQWarmLogo.png" alt="NurseQuizAI logo" className="lp-nav-logo" />
          NurseQuizAI
        </Link>
        <Link to="/signup" className="lp-nav-cta">Start Free →</Link>
      </nav>

      {/* ── HERO ── */}
      <header className="lp-hero">
        <div className="lp-hero-badge">✦ Powered by AI · Built for NCLEX</div>

        <h1 className="lp-h1">
          The <span className="lp-h1-accent">AI NCLEX Question Generator</span><br />
          That Uses Your Own Notes
        </h1>

        <p className="lp-hero-sub">
          Upload any nursing PDF, slide deck, or study guide and get unlimited
          NCLEX-style practice questions in seconds — tailored to exactly what
          you're studying, not some generic question bank.
        </p>

        <div className="lp-hero-ctas">
          <Link to="/signup" className="lp-btn-primary">
            Generate Questions Free →
          </Link>
          <Link to="/blog/best-nclex-study-strategies" className="lp-btn-secondary">
            See study strategies
          </Link>
        </div>

        <p className="lp-hero-proof">
          <span>Free to start</span>
          <span className="lp-hero-proof-dot" />
          <span>No credit card needed</span>
          <span className="lp-hero-proof-dot" />
          <span>Results in under 30 seconds</span>
        </p>
      </header>

      {/* ── DEMO CARD ── */}
      <div className="lp-demo-card" aria-label="Example NCLEX question generated by AI">
        <div className="lp-demo-inner">
          <div className="lp-demo-header">
            <span className="lp-demo-dot lp-demo-dot-red" />
            <span className="lp-demo-dot lp-demo-dot-yellow" />
            <span className="lp-demo-dot lp-demo-dot-green" />
            <span className="lp-demo-title">AI-Generated NCLEX Question — Pharmacology</span>
          </div>
          <div className="lp-demo-body">
            <div className="lp-demo-question-label">NCLEX-RN Style · Priority Question</div>
            <p className="lp-demo-question">
              A nurse is caring for a client who is receiving IV vancomycin for MRSA
              pneumonia. The client's trough level returns at 22 mcg/mL (therapeutic
              range 10–20 mcg/mL). Which action should the nurse take first?
            </p>
            <div className="lp-demo-options">
              <div className="lp-demo-option">
                <span className="lp-demo-option-letter">A</span>
                Administer the next dose as scheduled and recheck the trough
              </div>
              <div className="lp-demo-option">
                <span className="lp-demo-option-letter">B</span>
                Increase the IV infusion rate to promote faster distribution
              </div>
              <div className="lp-demo-option correct">
                <span className="lp-demo-option-letter">C</span>
                Hold the next dose and notify the healthcare provider
              </div>
              <div className="lp-demo-option">
                <span className="lp-demo-option-letter">D</span>
                Document the result and continue the current regimen
              </div>
            </div>
            <div className="lp-demo-rationale">
              <strong>✓ Correct — C.</strong> A supratherapeutic vancomycin trough (&gt;20 mcg/mL)
              increases the risk of nephrotoxicity and ototoxicity. The priority action is
              to hold the dose and notify the provider so the regimen can be adjusted.
              This question aligns with NCLEX priority/safety concepts.
            </div>
          </div>
        </div>
      </div>

      {/* ── STATS ── */}
      <section className="lp-stats" aria-label="Platform statistics">
        <div className="lp-stats-inner">
          <div>
            <div className="lp-stat-number">30s</div>
            <div className="lp-stat-label">Average time to generate your first quiz</div>
          </div>
          <div>
            <div className="lp-stat-number">10+</div>
            <div className="lp-stat-label">Question formats including NGN types</div>
          </div>
          <div>
            <div className="lp-stat-number">Any PDF</div>
            <div className="lp-stat-label">Upload notes, slides, or textbook chapters</div>
          </div>
          <div>
            <div className="lp-stat-number">Free</div>
            <div className="lp-stat-label">Start generating questions at no cost</div>
          </div>
        </div>
      </section>

      {/* ── HOW IT WORKS ── */}
      <section className="lp-section" aria-labelledby="how-it-works-title">
        <div className="lp-section-label">How it works</div>
        <h2 className="lp-section-title" id="how-it-works-title">
          From notes to NCLEX questions in 3 steps
        </h2>
        <p className="lp-section-sub">
          No complicated setup. Upload your material, let the AI do the work,
          and start practicing immediately.
        </p>

        <div className="lp-steps">
          <div className="lp-step">
            <div className="lp-step-number">1</div>
            <div className="lp-step-title">Upload your nursing notes</div>
            <p className="lp-step-desc">
              Drop in any PDF — lecture slides, professor handouts, ATI modules,
              Saunders chapters, your own handwritten notes scanned to PDF. Any
              nursing content works.
            </p>
          </div>
          <div className="lp-step">
            <div className="lp-step-number">2</div>
            <div className="lp-step-title">AI generates NCLEX questions</div>
            <p className="lp-step-desc">
              Our AI reads your material and generates multiple-choice, SATA,
              case study, and Next Generation NCLEX (NGN) questions — all mapped
              to NCLEX client needs categories.
            </p>
          </div>
          <div className="lp-step">
            <div className="lp-step-number">3</div>
            <div className="lp-step-title">Practice, review, pass</div>
            <p className="lp-step-desc">
              Answer questions, read AI-generated rationales, review flashcards,
              and track your weak areas. Everything you need to pass NCLEX — in
              one place.
            </p>
          </div>
        </div>
      </section>

      {/* ── QUESTION TYPES ── */}
      <section className="lp-section" aria-labelledby="question-types-title">
        <div className="lp-section-label">Question types</div>
        <h2 className="lp-section-title" id="question-types-title">
          Every NCLEX question format, covered
        </h2>
        <p className="lp-section-sub">
          The NCLEX tests you in multiple ways. Our AI question generator
          produces every format you'll face on exam day.
        </p>

        <div className="lp-qtypes">
          <div className="lp-qtype">
            <div className="lp-qtype-icon">☑️</div>
            <div className="lp-qtype-name">Multiple Choice</div>
            <p className="lp-qtype-desc">Classic NCLEX-style 4-option questions with rationales for every answer.</p>
            <span className="lp-qtype-badge">Most common</span>
          </div>
          <div className="lp-qtype">
            <div className="lp-qtype-icon">📋</div>
            <div className="lp-qtype-name">Select All That Apply</div>
            <p className="lp-qtype-desc">SATA questions that test deeper comprehension — the format most students struggle with.</p>
            <span className="lp-qtype-badge">High yield</span>
          </div>
          <div className="lp-qtype">
            <div className="lp-qtype-icon">🏥</div>
            <div className="lp-qtype-name">Case Studies (NGN)</div>
            <p className="lp-qtype-desc">Multi-question unfolding case studies for Next Generation NCLEX preparation.</p>
            <span className="lp-qtype-badge">NGN 2026</span>
          </div>
          <div className="lp-qtype">
            <div className="lp-qtype-icon">🃏</div>
            <div className="lp-qtype-name">Flashcards</div>
            <p className="lp-qtype-desc">Key terms, drug names, and concepts turned into spaced-repetition flashcard decks.</p>
          </div>
          <div className="lp-qtype">
            <div className="lp-qtype-icon">🧠</div>
            <div className="lp-qtype-name">Priority Questions</div>
            <p className="lp-qtype-desc">What would you do first? Safety and priority questions are NCLEX favorites.</p>
            <span className="lp-qtype-badge">High yield</span>
          </div>
          <div className="lp-qtype">
            <div className="lp-qtype-icon">🔊</div>
            <div className="lp-qtype-name">Audio Summaries</div>
            <p className="lp-qtype-desc">Listen to AI-generated audio summaries of your notes while commuting or at the gym.</p>
          </div>
        </div>
      </section>

      {/* ── FEATURES ── */}
      <section className="lp-section" aria-labelledby="features-title">
        <div className="lp-section-label">Why NurseQuizAI</div>
        <h2 className="lp-section-title" id="features-title">
          More than a question generator
        </h2>
        <p className="lp-section-sub">
          Generic NCLEX banks test you on other people's notes. NurseQuizAI
          tests you on yours — so you actually retain what you studied.
        </p>

        <div className="lp-features">
          <div className="lp-feature">
            <div className="lp-feature-icon">📄</div>
            <div>
              <div className="lp-feature-title">Your material, not someone else's</div>
              <p className="lp-feature-desc">
                Questions are generated directly from your uploaded PDFs and notes.
                If your professor emphasized fluid &amp; electrolytes, so will your quiz.
                No irrelevant filler.
              </p>
            </div>
          </div>
          <div className="lp-feature">
            <div className="lp-feature-icon">⚡</div>
            <div>
              <div className="lp-feature-title">Instant results — under 30 seconds</div>
              <p className="lp-feature-desc">
                Upload a 50-page pharmacology chapter and get a full quiz in
                seconds. No waiting, no manual setup, no flashcard app importing.
              </p>
            </div>
          </div>
          <div className="lp-feature">
            <div className="lp-feature-icon">💡</div>
            <div>
              <div className="lp-feature-title">Rationales that actually teach</div>
              <p className="lp-feature-desc">
                Every generated question comes with a detailed rationale explaining
                the correct answer and why the other options are wrong — just like
                Saunders but personalized.
              </p>
            </div>
          </div>
          <div className="lp-feature">
            <div className="lp-feature-icon">📊</div>
            <div>
              <div className="lp-feature-title">Track your weak areas</div>
              <p className="lp-feature-desc">
                The app identifies which topics you're getting wrong and surfaces
                more questions on those areas, so your study time goes where it
                matters most.
              </p>
            </div>
          </div>
          <div className="lp-feature">
            <div className="lp-feature-icon">🎯</div>
            <div>
              <div className="lp-feature-title">NCLEX client needs alignment</div>
              <p className="lp-feature-desc">
                Questions are automatically mapped to NCLEX client needs categories
                — Safe &amp; Effective Care, Health Promotion, Psychosocial Integrity,
                and Physiological Integrity.
              </p>
            </div>
          </div>
          <div className="lp-feature">
            <div className="lp-feature-icon">🗂️</div>
            <div>
              <div className="lp-feature-title">Study sheets &amp; mind maps</div>
              <p className="lp-feature-desc">
                Beyond questions — get AI-generated study sheets and visual mind
                maps from your notes so you can review concepts quickly before
                your exam.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* ── FAQ ── */}
      <section className="lp-section" aria-labelledby="faq-title">
        <div className="lp-section-label">FAQ</div>
        <h2 className="lp-section-title" id="faq-title">Common questions</h2>

        <div className="lp-faq" itemScope itemType="https://schema.org/FAQPage">
          {[
            {
              q: 'Is the AI NCLEX question generator free?',
              a: 'Yes — you can start generating NCLEX questions for free without a credit card. Upload your notes and get your first quiz immediately. Paid plans unlock unlimited uploads and advanced features.',
            },
            {
              q: 'What types of files can I upload?',
              a: 'You can upload PDF files including lecture slides, textbook chapters, ATI or Hesi modules, professor handouts, and scanned handwritten notes. The AI extracts the content and builds questions from it.',
            },
            {
              q: 'How is this different from Quizlet or UWorld?',
              a: 'Quizlet requires you to create flashcards manually. UWorld uses a fixed question bank. NurseQuizAI generates NCLEX questions directly from your own study material — so you\'re being tested on exactly what you\'re learning, not someone else\'s curriculum.',
            },
            {
              q: 'Does it support Next Generation NCLEX (NGN) questions?',
              a: 'Yes. The generator produces NGN formats including unfolding case studies, extended multiple response, matrix/grid questions, and trend items — the formats introduced in the updated NCLEX.',
            },
            {
              q: 'How accurate are the generated questions?',
              a: 'The AI generates questions based directly on your uploaded content and is designed to follow NCLEX question-writing standards. Each question includes a rationale grounded in the source material. We recommend using it alongside your instructor\'s guidance.',
            },
            {
              q: 'Can I use it for pharmacology and med-surg?',
              a: 'Absolutely. Upload your pharmacology notes and get drug-specific NCLEX questions covering mechanism of action, nursing considerations, adverse effects, and priority assessments. It works for any nursing specialty.',
            },
          ].map(({ q, a }) => (
            <div
              key={q}
              className="lp-faq-item"
              itemScope
              itemProp="mainEntity"
              itemType="https://schema.org/Question"
            >
              <h3 className="lp-faq-q" itemProp="name">{q}</h3>
              <div
                className="lp-faq-a"
                itemScope
                itemProp="acceptedAnswer"
                itemType="https://schema.org/Answer"
              >
                <div itemProp="text">{a}</div>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* ── FINAL CTA ── */}
      <div className="lp-cta-banner" role="complementary" aria-label="Call to action">
        <h2>Stop studying from other people's notes.</h2>
        <p>
          Generate NCLEX practice questions from your own material in 30 seconds.
          Free to start — no credit card required.
        </p>
        <Link to="/signup" className="lp-btn-primary">
          Generate My First Quiz →
        </Link>
        <p className="lp-cta-subtext">
          Already have an account? <Link to="/login" style={{ color: 'var(--primary-coral, #e88d7d)' }}>Log in</Link>
        </p>
      </div>

      {/* ── FOOTER ── */}
      <footer className="lp-footer">
        <p>
          © 2025 NurseQuizAI — AI-Powered NCLEX Question Generator
          <br />
          <Link to="/blog">Blog</Link>
          <Link to="/signup">Sign Up Free</Link>
          <Link to="/login">Log In</Link>
        </p>
      </footer>

    </div>
  );
};

export default NclexQuestionGenerator;
