export const courseStudioEn = {
  checkRecommendation: 'We analyzed your answers. Let’s start with {{topic}}.',
  materialsRecommendation: 'From your notes, let’s start with {{topic}}.',
  checkHeading: 'Your quick check',
  examDateQuestion: 'When is your exam?',
  examWelcome: 'Let’s get you ready for the exam.', examWelcomeWhen: 'When is your exam?', examWelcomeSkip: 'I don’t know yet',
  sourceTabs: 'Sources for your plan', documentsTab: 'Your documents', webTab: 'Web sources',
  viewAllDocuments: 'View all {{count}} documents', viewAllSources: 'View all {{count}} sources', closeSources: 'Close sources',
  searchOnline: 'Finding sources for more accurate preparation', searchComplete: 'Sources for more accurate preparation', searchInterrupted: 'Search interrupted',
  searchFinishedEmpty: 'Research complete',
  searchCourse: 'Course', searchInstructor: 'Instructor', searchReferences: 'Clinical references',
  searchResourceCount: '{{count}} resources found', searchResourceCount_one: '1 resource found',
  searchChecked: 'No additional findings', searchResumeHint: 'Continue with your files',
  searchCitationCount: '{{count}} citations found', searchCitationCount_one: '1 citation found',
  lessPassage: 'Show less',
  transformTitle: 'Your notes. Your exam-style quiz.',
  addCourseContext: 'Add course or exam details (optional)',
  processingFiles: 'Reading your uploaded files…',
  transformFailed: 'Your files are ready, but the quiz could not be prepared. Try again without uploading again.',
  retryQuestion: 'Try again',
  transformSub: 'Watch your course materials become a quiz you can try.',
  yourFiles: 'Your files', sourcePassage: 'The passage', examQuestion: 'Your quiz',
  foundPassage: 'FOUND IN YOUR UPLOAD', findingPassage: 'Finding a passage to build from…',
  formingQuestion: 'Building your quiz from your notes…',
  previewUnavailable: 'Continuing with your course materials.', seePassage: 'See passage',
  questionRevealTitle: 'Your notes just became a quiz.',
  questionRevealSub: 'Try it. Your answers will shape where you start.',
  label: 'YOUR PERSONAL STUDY BRIEF', setup: 'Your course', discover: 'Discover', check: 'Quick check', path: 'Your starting point',
  contextTitle: 'A little context. A much better plan.', contextSub: 'Add what you know. We’ll take it from here.',
  course: 'What are you studying?', coursePlaceholder: 'e.g. NURS 234 · Pharmacology', examDate: 'Exam date', optional: 'Optional',
  addDate: 'Add a date', details: 'Add exam details', detailsHint: 'Topics, format, or a note from your instructor',
  schoolDetails: 'Add school or instructor', school: 'School', schoolPlaceholder: 'Your school or university',
  professor: 'Instructor', professorPlaceholder: 'Instructor’s name', publicOnly: 'Used to find public course and academic information.',
  exam: 'What should we know about the exam?', examPlaceholder: 'e.g. Midterm on cardiovascular medications and diuretics. Multiple choice.',
  contextCta: 'Find what matters', materialsOnly: 'Continue with my files', readingFiles: 'Your files are processing', filesReady: 'Your materials are ready',
  files: '{{count}} files', oneFile: '1 file', noDate: 'No date needed to get started',
  readingTitle: 'Finding the thread in your materials.', readingSub: 'Your course is coming into focus. Here’s what we’re finding.',
  waitingTitle: 'Making room for your next chapter.', waitingSub: 'Your files are processing. Your first question starts here.',
  stageMaterials: 'Read your materials', stageContext: 'Connect the context', stageStrategy: 'Choose what matters',
  waiting: 'Waiting for your files', working: 'In progress', complete: 'Complete', optionalContext: 'Using available context',
  discovered: 'FOUND IN YOUR MATERIALS', topicsFound: '{{count}} topics identified',
  topicsFound_one: '1 topic identified', sourcesFound_one: '1 public source found', objectivesFound_one: '1 published objective found',
  sourcesFound: '{{count}} public sources found', objectivesFound: '{{count}} published objectives found',
  researchSlow: 'This is taking a little longer. You can continue with your materials whenever you’re ready.',
  continueMaterials: 'Continue with my materials', viewActivity: 'See research activity',
  briefTitle: 'Your course, made clearer.', briefSub: 'We’ve found the priorities in your materials. A short check will help us find your starting point.',
  materialsNote: 'Based on {{files}} files and {{topics}} topics', courseNote: 'Course context', evidence: 'Why this matters',
  initialOrder: 'COURSE PRIORITIES', adaptedOrder: 'YOUR STUDY ORDER', orderNote: 'A starting order based on your course. Your answers help make it personal.',
  adaptedNote: 'Your answers set the pace. Course priorities guide the order when results are tied.',
  questionsReady: '{{count}} questions · no grades', questionsPreparing: 'A short check · no grades',
  startCheck: 'Find my starting point', skipCheck: 'Build a plan without the check', explore: 'Explore the course findings',
  checkTitle: 'Let’s find your starting point.', checkSub: 'Answer what you can. “I’m not sure” helps us just as much.',
  questionCount: 'Question {{current}} of {{total}}', answerHint: 'Choose the best answer', unsure: 'I’m not sure yet',
  correctAnswer: 'Correct answer', correct: 'Correct', revisit: 'Answer review', unsureFeedback: 'Answer review',
  answer: 'The answer is {{answer}}.', next: 'Next question', seeResult: 'See my starting point', skipRemaining: 'Continue with what you know about me',
  quizLoading: 'Preparing your course questions.', quizLoadingSub: 'We’re using the topics in your brief to make this check relevant.',
  quizUnavailable: 'The quick check isn’t available right now. Your course-based plan is still ready to build.',
  resultTitle: 'A starting point that’s yours.', changedTitle: 'Your answers changed the starting point.',
  resultSub: 'An initial picture from {{count}} answers. We’ll keep learning with you as you study.',
  resultSub_one: 'An initial picture from your first answer. We’ll keep learning with you as you study.',
  skippedTitle: 'A clear place to begin.', skippedSub: 'We’ll begin with your course priorities and learn more about you as you study.',
  first: 'START HERE', nextUp: 'Up next', focus: 'Worth revisiting', sampled: 'Answered correctly', untested: 'Not checked yet',
  checkedCount: '{{correct}} of {{total}} in this check', moved: 'Moved from {{rank}}', review: 'Quick review',
  focusReason: 'Review: {{concepts}}.',
  sampleReason: 'You answered the sampled questions correctly. We’ll keep this in your review.',
  untestedReason: 'We haven’t checked this topic yet. It stays in your plan.',
  trimmed: '{{count}} topics deferred to fit your exam date.',
  trimmed_one: '1 topic deferred to fit your exam date.',
  sampleFoot: 'A starting signal, not a mastery score. Topics we haven’t checked stay untested.',
  build: 'Build my study plan', buildHint: 'Next: your activities, built from this starting point', replay: 'Replay the adjustment',
  empty: 'Your materials will guide the plan.', dateLabel: 'Exam on {{date}}', editDate: 'Change exam date',
  preparingPlan: 'Turning your starting point into a plan.', planSubtitle: 'Your course. Your answers. Your next step.',
  basedOnAnswers: 'Using your answers to choose where to begin', planStart: 'Start my first activity',
};

export const courseStudioFr = {
  checkRecommendation: 'Nous avons analysé vos réponses. Commençons par {{topic}}.',
  materialsRecommendation: 'D’après vos notes, commençons par {{topic}}.',
  checkHeading: 'Votre petit bilan',
  examDateQuestion: 'Quand a lieu votre examen ?',
  examWelcome: 'Préparons votre examen ensemble.', examWelcomeWhen: 'Quand a lieu votre examen ?', examWelcomeSkip: 'Je ne sais pas encore',
  sourceTabs: 'Sources de votre plan', documentsTab: 'Vos documents', webTab: 'Sources web',
  viewAllDocuments: 'Voir les {{count}} documents', viewAllSources: 'Voir les {{count}} sources', closeSources: 'Fermer les sources',
  searchOnline: 'Recherche de sources pour mieux cibler votre préparation', searchComplete: 'Des sources pour mieux cibler votre préparation', searchInterrupted: 'Recherche interrompue',
  searchFinishedEmpty: 'Recherche terminée',
  searchCourse: 'Cours', searchInstructor: 'Professeur', searchReferences: 'Références cliniques',
  searchResourceCount: '{{count}} ressources trouvées', searchResourceCount_one: '1 ressource trouvée',
  searchChecked: 'Aucun résultat supplémentaire', searchResumeHint: 'Continuer avec vos fichiers',
  searchCitationCount: '{{count}} références trouvées', searchCitationCount_one: '1 référence trouvée',
  lessPassage: 'Réduire',
  transformTitle: 'Vos notes. Votre quiz d’entraînement.',
  addCourseContext: 'Ajouter des détails sur le cours ou l’examen (facultatif)',
  processingFiles: 'Lecture de vos fichiers…',
  transformFailed: 'Vos fichiers sont prêts, mais le quiz n’a pas pu être préparé. Réessayez sans téléverser à nouveau.',
  retryQuestion: 'Réessayer',
  transformSub: 'Vos documents de cours deviennent un quiz à essayer.',
  yourFiles: 'Vos fichiers', sourcePassage: 'Le passage', examQuestion: 'Votre quiz',
  foundPassage: 'DANS VOTRE DOCUMENT', findingPassage: 'Recherche d’un passage pertinent…',
  formingQuestion: 'Création de votre quiz à partir de vos notes…',
  previewUnavailable: 'Nous continuons avec vos documents.', seePassage: 'Voir le passage',
  questionRevealTitle: 'Vos notes sont devenues un quiz.',
  questionRevealSub: 'Essayez. Vos réponses guideront votre point de départ.',
  label: 'VOTRE FEUILLE DE ROUTE', setup: 'Votre cours', discover: 'Découverte', check: 'Petit bilan', path: 'Votre point de départ',
  contextTitle: 'Un peu de contexte. Un plan qui vous ressemble.', contextSub: 'Ajoutez ce que vous savez. On s’occupe de la suite.',
  course: 'Qu’étudiez-vous ?', coursePlaceholder: 'Ex. NURS 234 · Pharmacologie', examDate: 'Date de l’examen', optional: 'Facultatif',
  addDate: 'Ajouter une date', details: 'Préciser l’examen', detailsHint: 'Sujets, format ou consignes de votre professeur',
  schoolDetails: 'Ajouter l’école ou le professeur', school: 'École', schoolPlaceholder: 'Votre école ou université',
  professor: 'Professeur', professorPlaceholder: 'Nom du professeur', publicOnly: 'Pour trouver des informations publiques sur le cours et le professeur.',
  exam: 'Que faut-il savoir sur l’examen ?', examPlaceholder: 'Ex. Intra sur les médicaments cardiovasculaires et les diurétiques. Choix multiples.',
  contextCta: 'Trouver les priorités', materialsOnly: 'Continuer avec mes fichiers', readingFiles: 'Traitement de vos fichiers', filesReady: 'Vos documents sont prêts',
  files: '{{count}} fichiers', oneFile: '1 fichier', noDate: 'Vous pouvez commencer sans date',
  readingTitle: 'Vos documents prennent tout leur sens.', readingSub: 'Votre cours se précise. Voici ce qui se dessine.',
  waitingTitle: 'Votre prochain chapitre se prépare.', waitingSub: 'Vos fichiers sont en cours de traitement. Votre première question commence ici.',
  stageMaterials: 'Lire vos documents', stageContext: 'Relier le contexte', stageStrategy: 'Trouver les priorités',
  waiting: 'En attente des fichiers', working: 'En cours', complete: 'Terminé', optionalContext: 'Avec le contexte disponible',
  discovered: 'DANS VOS DOCUMENTS', topicsFound: '{{count}} sujets identifiés',
  topicsFound_one: '{{count}} sujet identifié', sourcesFound_one: '{{count}} source publique trouvée', objectivesFound_one: '{{count}} objectif publié trouvé',
  sourcesFound: '{{count}} sources publiques trouvées', objectivesFound: '{{count}} objectifs publiés trouvés',
  researchSlow: 'Cela prend un peu plus de temps. Vous pouvez continuer avec vos documents dès que vous le souhaitez.',
  continueMaterials: 'Continuer avec mes documents', viewActivity: 'Voir la recherche en détail',
  briefTitle: 'Votre cours, plus clair.', briefSub: 'Nous avons repéré les priorités dans vos documents. Un petit bilan nous aidera à trouver votre point de départ.',
  materialsNote: 'À partir de {{files}} fichiers et de {{topics}} sujets', courseNote: 'Contexte du cours', evidence: 'Pourquoi ce sujet compte',
  initialOrder: 'PRIORITÉS DU COURS', adaptedOrder: 'VOTRE ORDRE D’ÉTUDE', orderNote: 'Un premier ordre fondé sur votre cours. Vos réponses le rendent personnel.',
  adaptedNote: 'Vos réponses guident le rythme. À résultats égaux, les priorités du cours déterminent l’ordre.',
  questionsReady: '{{count}} questions · sans note', questionsPreparing: 'Un petit bilan · sans note',
  startCheck: 'Trouver mon point de départ', skipCheck: 'Créer un plan sans le bilan', explore: 'Explorer les découvertes',
  checkTitle: 'Trouvons votre point de départ.', checkSub: 'Répondez comme vous pouvez. « Je ne sais pas encore » nous aide aussi.',
  questionCount: 'Question {{current}} sur {{total}}', answerHint: 'Choisissez la meilleure réponse', unsure: 'Je ne sais pas encore',
  correctAnswer: 'Bonne réponse', correct: 'Correct', revisit: 'Explication', unsureFeedback: 'Explication',
  answer: 'La réponse est : {{answer}}.', next: 'Question suivante', seeResult: 'Voir mon point de départ', skipRemaining: 'Continuer avec ce bilan',
  quizLoading: 'Vos questions se préparent.', quizLoadingSub: 'Nous utilisons les sujets de votre cours pour rendre ce bilan pertinent.',
  quizUnavailable: 'Le bilan n’est pas disponible pour le moment. Vous pouvez créer un plan à partir de votre cours.',
  resultTitle: 'Un point de départ qui vous ressemble.', changedTitle: 'Vos réponses ont changé le point de départ.',
  resultSub: 'Un premier aperçu à partir de {{count}} réponses. Nous continuerons à apprendre avec vous.',
  resultSub_one: 'Un premier aperçu à partir de votre première réponse. Nous continuerons à apprendre avec vous.',
  skippedTitle: 'Un point de départ clair.', skippedSub: 'Nous partirons des priorités du cours et apprendrons à mieux vous connaître en chemin.',
  first: 'COMMENCEZ ICI', nextUp: 'Ensuite', focus: 'À revoir ensemble', sampled: 'Réponses correctes', untested: 'Pas encore évalué',
  checkedCount: '{{correct}} sur {{total}} dans ce bilan', moved: 'Depuis la place {{rank}}', review: 'Révision rapide',
  focusReason: 'À revoir : {{concepts}}.',
  sampleReason: 'Vous avez répondu correctement aux questions proposées. Ce sujet reste dans vos révisions.',
  untestedReason: 'Nous n’avons pas encore évalué ce sujet. Il reste dans votre plan.',
  trimmed: 'Le plan tient compte de la date de l’examen ; {{count}} sujets sont reportés.',
  trimmed_one: 'Le plan tient compte de la date de l’examen ; 1 sujet est reporté.',
  sampleFoot: 'Un premier indice, pas un score de maîtrise. Les sujets non évalués restent à découvrir.',
  build: 'Créer mon plan d’étude', buildHint: 'Ensuite : vos activités, adaptées à ce point de départ', replay: 'Revoir l’ajustement',
  empty: 'Vos documents guideront le plan.', dateLabel: 'Examen le {{date}}', editDate: 'Changer la date',
  preparingPlan: 'Votre point de départ devient un plan.', planSubtitle: 'Votre cours. Vos réponses. Votre prochaine étape.',
  basedOnAnswers: 'Vos réponses nous aident à choisir par où commencer', planStart: 'Commencer ma première activité',
};
